### ISSUE TITLE
Mastering To-Do list for publishing

### ISSUE THREAD

**Issue by vv-monsalve** [benhoepner/National-Park#12]
Summarizing the steps needed:

### Range revision

Before working on the outlines fixes, please review the range to reduce the number of masters and so ease the job.

- [x] Review the axis range and progression to better define the weight values for each instance
- [x] Once the above is done, use the "Instance as Master" option to create a Regular master to work only with three masters: `ExtraLight`, `Regular`, `ExtraBold`
- [x] Replicate the decisions/process in the Stencil file to keep the in sync

### Outlines
- [x] #15
- [x] Relieve the junctions whenever possible (especially in the ExtraBold weight) e.g. `n` `a`
- [ ] Improve the Monetry symbols. Creating a system for the bars and using the [bracket layer](https://glyphsapp.com/learn/alternating-glyph-shapes)
- [x] Add the five missing glyphs to comply with GF Latin Core. Review the existing glyphs marked as non-exportable 
- [x] #16
   - https://glyphsapp.com/learn/fractions
   - https://glyphsapp.com/learn/figure-sets
- [x] Please make sure the punctuation spacing and kerning is ok. E.g. exclamation spacing look a bit tight; and LY and other common kerning cases
- [x] Ensure loclCAT is working ok. [Glyphs app tutorial](https://glyphsapp.com/learn/localize-your-font-catalan-punt-volat) as reference

**Comment by vv-monsalve** [comment]
### Repo structure the project

- [ ] Solving the problem of GHA `build` to build and test the sources and recover CI capabilities - Merging [Simon's PR](https://github.com/benhoepner/National-Park/pull/11)
- [ ] Include build instructions in the README file
- [ ] Please provide more detailed information in the README file. You can read about this file in our [documentation](https://googlefonts.github.io/gf-guide/readmefile.html).
- [ ] Include a sample image in the README file
- [ ] Either adjust or remove the [trademark file](https://googlefonts.github.io/gf-guide/requirements.html#trademarks).

**Comment by vv-monsalve** [comment]
### Production

- [ ] Review vertical metrics to meet GF standard
- [ ] Create a cursive axis to activate the schoolbook glyphs

**Comment by aherstowski** [comment]
> ### Repo structure the project
> * [ ]  Solving the problem of GHA `build` to build and test the sources and recover CI capabilities - Merging [Simon's PR](https://github.com/benhoepner/National-Park/pull/11)
> * [ ]  Please provide more detailed information in the README file. You can read about this file in our [documentation](https://googlefonts.github.io/gf-guide/readmefile.html).
> * [ ]  Include a sample image in the README file
> * [x]  Remove the [trademark file](https://googlefonts.github.io/gf-guide/requirements.html#trademarks).

@vv-monsalve 
when I first picked the project back up I think i didn't get Simon's PR merged, is there a way to get the "build" again?
working on the Read Me should have it done soon.

**Comment by aherstowski** [comment]
> Summarizing the steps needed:
> 
> ### Range revision
> Before working on the outlines fixes, please review the range to reduce the number of masters and so ease the job.
> 
> * [ ]  Review the axis range and progression to better define the weight values for each instance
> * [ ]  Once the above is done, use the "Instance as Master" option to create a Regular master to work only with three masters: `ExtraLight`, `Regular`, `ExtraBold`
> * [ ]  Replicate the decisions/process in the Stencil file to keep the in sync
> 
> ### Outlines
> * [x]  [Ensure all the horizontal stems (bars) are thinner than vertical ones (to prevent them from looking thicker) #15](https://github.com/benhoepner/National-Park/issues/15)
> * [x]  Relieve the junctions whenever possible (especially in the ExtraBold weight) e.g. `n` `a`
> * [ ]  Improve the Monetry symbols. Creating a system for the bars and using the [bracket layer](https://glyphsapp.com/learn/alternating-glyph-shapes)
> * [x]  Add the five missing glyphs to comply with GF Latin Core. Review the existing glyphs marked as non-exportable
> * [x]  [Review / adjust the figures, particularly: superiors and fractions #16](https://github.com/benhoepner/National-Park/issues/16)
>   
>   * https://glyphsapp.com/learn/fractions
>   * https://glyphsapp.com/learn/figure-sets
> * [ ]  Please make sure the punctuation spacing and kerning is ok. E.g. exclamation spacing look a bit tight; and LY and other common kerning cases
> * [x]  Ensure loclCAT is working ok. [Glyphs app tutorial](https://glyphsapp.com/learn/localize-your-font-catalan-punt-volat) as reference

@vv-monsalve I am close with the list. 
Could you show me the Kern Group again, at the time I thought I had it but now that I am ready to do it I am not sure. 

I have the monetary symbols corrected, I haven't turned the bars into outlines yet they are still strokes. Can you look at a couple and see if you still think I need to do the Bracket Layer?

been going glyph by glyph to check things. think once the monetary are done, finish up kerning and then will do the axis range/instance master... :) *I see now that you had me do that first but doing it last eek!

**Comment by vv-monsalve** [comment]
@aherstowski I'll pull the latest file, check everything (including the monetary symbols), and create tabs in the source file again with the lists to check the kerning.

> *I see now that you had me do that first but doing it last eek!

Indeed! The idea was to reduce the number of masters first, so it would be one less to work on ':-D

**Comment by vv-monsalve** [comment]
> Could you show me the Kern Group again, at the time I thought I had it but now that I am ready to do it I am not sure.

Do you mean how to create them? If so I couldn't explain it better than how it's done in the [Glyphs App tutorial for Kerning](https://glyphsapp.com/learn/kerning) :)

**Comment by vv-monsalve** [comment]
Closing this here as separate issues were created to follow up kerning #22 and the Readme file #23
